POST  http://localhost:3002/api/blogs HTTP/1.1
content-type: application/json

 {
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7
  }